version: '3.8'

services:
  backend:
    image: kalpesh0524/backend  # ✅ exact repo name
    build: ./backend
    ports:
      - "5003:5003"
    env_file:
      - ./backend/.env
    working_dir: /app
